version: '3.7'

services:
  app-um:
    build: .
    container_name: app-um
    environment:
      - "TZ=${TIME_ZONE}"
    command: yarn start:${NODE_ENV}
    volumes:
      - .:/home/node/api
      - ./node_modules:/home/node/api/node_modules
    ports:
      - '3333:3333'
    networks:
      - app-um-network

networks:
  app-um-network:
    name: app-um-network
    driver: bridge
